### ISSUE TITLE
Generator is not working

### ISSUE THREAD

**Issue by deep12650** [yiimaker/yii2-email-templates#14]
Hello Team,
You guys really did the good work. I have integrated it into my application as defined I am using a yii2 advance template but unable to add in GII tools.  I have added following code to my `frontend/config/main.php` in component section:

```
'modules' => [
        'class' => 'yii\gii\Module',
            'generators' => [
                'email-templates' => [
                    'class' => \ymaker\email\templates\gii\Generator::class,
                    'templates' => [
                        'default' => '@vendor/yiimaker/yii2-email-templates/src/gii/default',
                    ],
                ],
            ],
    ],
```

Could you please guide me to implement it. I tried all ways and ran migration tool but no success. It is not showing email template generator in GII.

**Comment by greeflas** [comment]
@deep12650 Hi, thank you! Check your `frontend/config/main-local.php` configuration file. In advance template configuration for Gii stored in that file.

**Comment by deep12650** [comment]
Thanks for your answer. I just put this code as per your document, I am getting error in ./yii migrate:
'controllerMap' => [
```
        'fixture' => [
            'class' => 'yii\console\controllers\FixtureController',
            'namespace' => 'common\fixtures',
          ],
        'migrate' => [
            'migrationNamespaces' => [
                'ymaker\email\templates\migrations',
            ],
        ],
    ],
```
Error:
```
Exception 'yii\base\InvalidConfigException' with message 'Object configuration must be an array containing a "class" element.'

in /Applications/MAMP/htdocs/zyv/vendor/yiisoft/yii2/BaseYii.php:353

Stack trace:
#0 /Applications/MAMP/htdocs/zyv/vendor/yiisoft/yii2/base/Module.php(583): yii\BaseYii::createObject(Array, Array)
#1 /Applications/MAMP/htdocs/zyv/vendor/yiisoft/yii2/base/Module.php(522): yii\base\Module->createController('')
#2 /Applications/MAMP/htdocs/zyv/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate', Array)
#3 /Applications/MAMP/htdocs/zyv/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate', Array)
#4 /Applications/MAMP/htdocs/zyv/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#5 /Applications/MAMP/htdocs/zyv/yii(27): yii\base\Application->run()
#6 {main}
```

**Comment by greeflas** [comment]
@deep12650 You don't set name of migration class controller. In your case configuration should be like following:
```php
'migrate' => [
    'class' => 'yii\console\controllers\MigrateController',
    'migrationNamespaces' => [
        'ymaker\email\templates\migrations',
     ],
],
```

Please, read official Yii documentation for more info
http://www.yiiframework.com/doc-2.0/yii-console-controllers-migratecontroller.html
