### ISSUE TITLE
Interface as parameter in constructor

### ISSUE THREAD

**Issue by Geoffry304** [yiimaker/yii2-email-templates#27]
Hello,

I have an error on the latest version, I think the problem is the interface class as the paramter in the construct method of templatemanager.php

Exception (Not instantiable) 'yii\di\NotInstantiableException' with message 'Can not instantiate ymaker\email\templates\repositories\EmailTemplatesRepositoryInterface.' 

```
in C:\xampp\htdocs\veto\vendor\yiisoft\yii2\di\Container.php:372

Stack trace:
#0 C:\xampp\htdocs\veto\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('ymaker\\email\\te...', Array, Array)
#1 C:\xampp\htdocs\veto\vendor\yiisoft\yii2\di\Container.php(462): yii\di\Container->get('ymaker\\email\\te...')
#2 C:\xampp\htdocs\veto\vendor\yiisoft\yii2\di\Container.php(370): yii\di\Container->resolveDependencies(Array, Object(ReflectionClass))
#3 C:\xampp\htdocs\veto\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('ymaker\\email\\te...', Array, Array)
#4 C:\xampp\htdocs\veto\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('ymaker\\email\\te...', Array, Array)
#5 C:\xampp\htdocs\veto\vendor\yiisoft\yii2\di\ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#6 C:\xampp\htdocs\veto\vendor\yiisoft\yii2\base\Module.php(742): yii\di\ServiceLocator->get('templateManager', false)
#7 C:\xampp\htdocs\veto\models\Mail.php(175): yii\base\Module->get('templateManager', false)
#8 C:\xampp\htdocs\veto\controllers\MailController.php(45): app\models\Mail->setCorrectTemplate()
#9 [internal function]: app\controllers\MailController->actionCreate()
#10 C:\xampp\htdocs\veto\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\veto\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\veto\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('create', Array)
#13 C:\xampp\htdocs\veto\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('mail/create', Array)
#14 C:\xampp\htdocs\veto\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#15 C:\xampp\htdocs\veto\web\index.php(12): yii\base\Application->run()
#16 {main}
```

**Comment by Geoffry304** [comment]
I think it can be fixed of you change EmailTemplatesRepositoryInterface to EmailTemplatesRepository

**Comment by Geoffry304** [comment]
#28

**Comment by greeflas** [comment]
Hi @Geoffry304! I think you just need to configure your DI container like described in the guide
https://github.com/yiimaker/yii2-email-templates/blob/master/docs/guide/template-manager.md#configuration

**Comment by Geoffry304** [comment]
Hi @greeflas  thanks for the info, I will look into this!
